### ISSUE TITLE
Problems while install via pip

### ISSUE THREAD

**Issue by omazilov** [pklaus/bottlelog#2]
```
root@ThinkPad-X230:~# pip install bottlelog
Downloading/unpacking bottlelog
Could not find any downloads that satisfy the requirement bottlelog
No distributions at all found for bottlelog
Storing complete log in /home/user/.pip/pip.log
```

pip.log

```
------------------------------------------------------------
/usr/bin/pip run on Mon Aug 17 18:50:58 2015
Downloading/unpacking bottlelog
  Getting page http://pypi.python.org/simple/bottlelog
  Could not fetch URL http://pypi.python.org/simple/bottlelog: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/bottlelog when looking for download links for bottlelog
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for bottlelog:
  * http://pypi.python.org/simple/bottlelog/
  Getting page http://pypi.python.org/simple/bottlelog/
  Could not fetch URL http://pypi.python.org/simple/bottlelog/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/bottlelog/ when looking for download links for bottlelog
  Could not find any downloads that satisfy the requirement bottlelog
No distributions at all found for bottlelog
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 948, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 152, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for bottlelog
```

**Comment by pklaus** [comment]
Thanks for reporting this issue. I fixed this by updating the installation instructructions in the readme file:

```
pip install https://github.com/pklaus/bottlelog/archive/master.zip
```

But please note the big hint to [wsgi-request-logger](https://github.com/pklaus/wsgi-request-logger) also found in the README file. It's the successor of this project and doesn't have the deficiencies bottlelog suffered from.
